version: 2

defaults: &defaults
  working_directory: ~/graphql-page_cursors
  docker:
    - image: ruby:2.7.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Gem install bundler
          command: gem update --system && gem install bundler

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Gem install bundler
          command: gem update --system && gem install bundler

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rake

  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems

      - run:
          name: Build gem
          command: gem build graphql-page_cursors.gemspec --output graphql-page_cursors.gem

      - run:
          name: Publish gem
          command: gem push graphql-page_cursors.gem

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
  release:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
